"""
MAVLink protocol implementation (auto-generated by mavgen.py)

Generated from: ('ai-gp-protocol.xml',)

Note: this file has been auto-generated. DO NOT EDIT
"""
import hashlib
import json
import logging
import os
import struct
import sys
import time
from builtins import object, range
from typing import Any, Callable, Dict, Iterable, List, Mapping, Optional, Sequence, Tuple, Type, Union

WIRE_PROTOCOL_VERSION = "2.0"
DIALECT = "ai-gp-protocol"

PROTOCOL_MARKER_V1 = 0xFE
PROTOCOL_MARKER_V2 = 0xFD
HEADER_LEN_V1 = 6
HEADER_LEN_V2 = 10

MAVLINK_SIGNATURE_BLOCK_LEN = 13

MAVLINK_IFLAG_SIGNED = 0x01

logger = logging.getLogger(__name__)

# allow MAV_IGNORE_CRC=1 to ignore CRC, allowing some
# corrupted msgs to be seen
MAVLINK_IGNORE_CRC = os.environ.get("MAV_IGNORE_CRC", 0)

# some base types from mavlink_types.h
MAVLINK_TYPE_CHAR = 0
MAVLINK_TYPE_UINT8_T = 1
MAVLINK_TYPE_INT8_T = 2
MAVLINK_TYPE_UINT16_T = 3
MAVLINK_TYPE_INT16_T = 4
MAVLINK_TYPE_UINT32_T = 5
MAVLINK_TYPE_INT32_T = 6
MAVLINK_TYPE_UINT64_T = 7
MAVLINK_TYPE_INT64_T = 8
MAVLINK_TYPE_FLOAT = 9
MAVLINK_TYPE_DOUBLE = 10

# CRC calculation using fastcrc, falling back to a pure Python implementation
# if fastcrc is not available
try:
    import fastcrc
    mcrf4xx = fastcrc.crc16.mcrf4xx
except Exception:
    mcrf4xx = None  # type: ignore


BytesLike = Union[List[int], Tuple[int], bytes, bytearray, str]


class _x25crc_slow(object):
    """CRC-16/MCRF4XX - based on checksum.h from mavlink library"""

    crc: int

    def __init__(self, buf: Optional[BytesLike] = None):
        self.crc = 0xFFFF
        if buf is not None:
            self.accumulate(buf)

    def accumulate(self, buf: BytesLike) -> None:
        """add in some more bytes (it also accepts strings)"""
        if isinstance(buf, str):
            buf = buf.encode()

        accum = self.crc
        for b in buf:
            tmp = b ^ (accum & 0xFF)
            tmp = (tmp ^ (tmp << 4)) & 0xFF
            accum = (accum >> 8) ^ (tmp << 8) ^ (tmp << 3) ^ (tmp >> 4)
        self.crc = accum


class _x25crc_fast(object):
    """CRC-16/MCRF4XX - based on checksum.h from mavlink library"""

    def __init__(self, buf: Optional[BytesLike] = None):
        self.crc = 0xFFFF
        if buf is not None:
            self.accumulate(buf)

    def accumulate(self, buf: BytesLike) -> None:
        """add in some more bytes (it also accepts strings)"""
        if isinstance(buf, str):
            buf_as_bytes = bytes(buf.encode())
        elif isinstance(buf, (list, tuple, bytearray)):
            buf_as_bytes = bytes(buf)
        else:
            buf_as_bytes = buf
        self.crc = mcrf4xx(buf_as_bytes, self.crc)


x25crc = _x25crc_fast if mcrf4xx is not None else _x25crc_slow


class MAVLink_header(object):
    """MAVLink message header"""

    def __init__(self, msgId: int, incompat_flags: int = 0, compat_flags: int = 0, mlen: int = 0, seq: int = 0, srcSystem: int = 0, srcComponent: int = 0) -> None:
        self.mlen = mlen
        self.seq = seq
        self.srcSystem = srcSystem
        self.srcComponent = srcComponent
        self.msgId = msgId
        self.incompat_flags = incompat_flags
        self.compat_flags = compat_flags

    def pack(self, force_mavlink1: bool = False) -> bytes:
        if float(WIRE_PROTOCOL_VERSION) == 2.0 and not force_mavlink1:
            return struct.pack(
                "<BBBBBBBHB",
                253,
                self.mlen,
                self.incompat_flags,
                self.compat_flags,
                self.seq,
                self.srcSystem,
                self.srcComponent,
                self.msgId & 0xFFFF,
                self.msgId >> 16,
            )
        return struct.pack(
            "<BBBBBB",
            PROTOCOL_MARKER_V1,
            self.mlen,
            self.seq,
            self.srcSystem,
            self.srcComponent,
            self.msgId,
        )


class MAVLink_message(object):
    """base MAVLink message class"""

    id = 0
    msgname = ""
    fieldnames: List[str] = []
    ordered_fieldnames: List[str] = []
    fieldtypes: List[str] = []
    fielddisplays_by_name: Dict[str, str] = {}
    fieldenums_by_name: Dict[str, str] = {}
    fieldunits_by_name: Dict[str, str] = {}
    native_format = bytearray(b"")
    orders: List[int] = []
    lengths: List[int] = []
    array_lengths: List[int] = []
    crc_extra = 0
    unpacker = struct.Struct("")
    instance_field: Optional[str] = None
    instance_offset = -1

    def __init__(self, msgId: int, name: str) -> None:
        self._header = MAVLink_header(msgId)
        self._payload: Optional[bytes] = None
        self._msgbuf = bytearray(b"")
        self._crc: Optional[int] = None
        self._fieldnames: List[str] = []
        self._type = name
        self._signed = False
        self._link_id: Optional[int] = None
        self._instances: Optional[Dict[str, str]] = None
        self._instance_field: Optional[str] = None

    def format_attr(self, field: str) -> Union[str, float, int]:
        """override field getter"""
        raw_attr: Union[bytes, float, int] = getattr(self, field)
        if isinstance(raw_attr, bytes):
            return raw_attr.decode(errors="backslashreplace").rstrip("\x00")
        return raw_attr

    def get_msgbuf(self) -> bytearray:
        return self._msgbuf

    def get_header(self) -> MAVLink_header:
        return self._header

    def get_payload(self) -> Optional[bytes]:
        return self._payload

    def get_crc(self) -> Optional[int]:
        return self._crc

    def get_fieldnames(self) -> List[str]:
        return self._fieldnames

    def get_type(self) -> str:
        return self._type

    def get_msgId(self) -> int:
        return self._header.msgId

    def get_srcSystem(self) -> int:
        return self._header.srcSystem

    def get_srcComponent(self) -> int:
        return self._header.srcComponent

    def get_seq(self) -> int:
        return self._header.seq

    def get_signed(self) -> bool:
        return self._signed

    def get_link_id(self) -> Optional[int]:
        return self._link_id

    def __str__(self) -> str:
        ret = "%s {" % self._type
        for a in self._fieldnames:
            v = self.format_attr(a)
            ret += "%s : %s, " % (a, v)
        ret = ret[0:-2] + "}"
        return ret

    def __ne__(self, other: object) -> bool:
        return not self.__eq__(other)

    def __eq__(self, other: object) -> bool:
        if other is None:
            return False

        if not isinstance(other, MAVLink_message):
            return False

        if self.get_type() != other.get_type():
            return False

        if self.get_crc() != other.get_crc():
            return False

        if self.get_seq() != other.get_seq():
            return False

        if self.get_srcSystem() != other.get_srcSystem():
            return False

        if self.get_srcComponent() != other.get_srcComponent():
            return False

        for a in self._fieldnames:
            if self.format_attr(a) != other.format_attr(a):
                return False

        return True

    def to_dict(self) -> Dict[str, Union[str, float, int]]:
        d: Dict[str, Union[str, float, int]] = {}
        d["mavpackettype"] = self._type
        for a in self._fieldnames:
            d[a] = self.format_attr(a)
        return d

    def to_json(self) -> str:
        return json.dumps(self.to_dict())

    def sign_packet(self, mav: "MAVLink") -> None:
        assert mav.signing.secret_key is not None

        h = hashlib.new("sha256")
        self._msgbuf += struct.pack("<BQ", mav.signing.link_id, mav.signing.timestamp)[:7]
        h.update(mav.signing.secret_key)
        h.update(self._msgbuf)
        sig = h.digest()[:6]
        self._msgbuf += sig
        mav.signing.timestamp += 1

    def _pack(self, mav: "MAVLink", crc_extra: int, payload: bytes, force_mavlink1: bool = False) -> bytes:
        plen = len(payload)
        if float(WIRE_PROTOCOL_VERSION) == 2.0 and not force_mavlink1:
            # in MAVLink2 we can strip trailing zeros off payloads. This allows for simple
            # variable length arrays and smaller packets
            nullbyte = 0
            while plen > 1 and payload[plen - 1] == nullbyte:
                plen -= 1
        self._payload = payload[:plen]
        incompat_flags = 0
        if mav.signing.sign_outgoing:
            incompat_flags |= MAVLINK_IFLAG_SIGNED
        self._header = MAVLink_header(
            self._header.msgId,
            incompat_flags=incompat_flags,
            compat_flags=0,
            mlen=len(self._payload),
            seq=mav.seq,
            srcSystem=mav.srcSystem,
            srcComponent=mav.srcComponent,
        )
        self._msgbuf = bytearray(self._header.pack(force_mavlink1=force_mavlink1))
        self._msgbuf += self._payload
        crc = x25crc(self._msgbuf[1:])
        if True:
            # we are using CRC extra
            crc.accumulate(struct.pack("B", crc_extra))
        self._crc = crc.crc
        self._msgbuf += struct.pack("<H", self._crc)
        if mav.signing.sign_outgoing and not force_mavlink1:
            self.sign_packet(mav)
        return bytes(self._msgbuf)

    def pack(self, mav: "MAVLink", force_mavlink1: bool = False) -> bytes:
        raise NotImplementedError("MAVLink_message cannot be serialized directly")

    def __getitem__(self, key: str) -> str:
        """support indexing, allowing for multi-instance sensors in one message"""
        if self._instances is None:
            raise IndexError()
        if key not in self._instances:
            raise IndexError()
        return self._instances[key]


class mavlink_msg_deprecated_name_property(object):
    """
    This handles the class variable name change from name to msgname for
    subclasses of MAVLink_message during a transition period.

    This is used by setting the class variable to
    `mavlink_msg_deprecated_name_property()`.
    """

    def __get__(self, instance: Optional[MAVLink_message], owner: Type[MAVLink_message]) -> str:
        if instance is not None:
            logger.error("Using .name on a MAVLink_message is not supported, use .get_type() instead.")
            raise AttributeError("Class {} has no attribute 'name'".format(owner.__name__))
        logger.warning(
            """Using .name on a MAVLink_message class is deprecated, consider using .msgname instead.
Note that if compatibility with pymavlink 2.4.30 and earlier is desired, use something like this:

msg_name =  msg.msgname if hasattr(msg, "msgname") else msg.name"""
        )
        return owner.msgname


# enums


class EnumEntry(object):
    def __init__(self, name: str, description: str) -> None:
        self.name = name
        self.description = description
        self.param: Dict[int, str] = {}
        self.has_location = False

class Enum(Dict[int, EnumEntry]):
    def __init__(self) -> None:
        self.bitmask = False

enums: Dict[str, Enum] = {}

# MAV_TYPE
enums["MAV_TYPE"] = Enum()
enums["MAV_TYPE"].bitmask = False
MAV_TYPE_GENERIC = 0
enums["MAV_TYPE"][0] = EnumEntry("MAV_TYPE_GENERIC", """Generic micro air vehicle.""")
MAV_TYPE_QUADROTOR = 2
enums["MAV_TYPE"][2] = EnumEntry("MAV_TYPE_QUADROTOR", """Quadrotor.""")
MAV_TYPE_ONBOARD_CONTROLLER = 27
enums["MAV_TYPE"][27] = EnumEntry("MAV_TYPE_ONBOARD_CONTROLLER", """Onboard companion controller.""")
MAV_TYPE_ENUM_END = 28
enums["MAV_TYPE"][28] = EnumEntry("MAV_TYPE_ENUM_END", """""")

# MAV_AUTOPILOT
enums["MAV_AUTOPILOT"] = Enum()
enums["MAV_AUTOPILOT"].bitmask = False
MAV_AUTOPILOT_GENERIC = 0
enums["MAV_AUTOPILOT"][0] = EnumEntry("MAV_AUTOPILOT_GENERIC", """Generic autopilot, full support for everything.""")
MAV_AUTOPILOT_INVALID = 8
enums["MAV_AUTOPILOT"][8] = EnumEntry("MAV_AUTOPILOT_INVALID", """No valid autopilot (e.g. a GCS or MAVLink component).""")
MAV_AUTOPILOT_ENUM_END = 9
enums["MAV_AUTOPILOT"][9] = EnumEntry("MAV_AUTOPILOT_ENUM_END", """""")

# MAV_MODE_FLAG
enums["MAV_MODE_FLAG"] = Enum()
enums["MAV_MODE_FLAG"].bitmask = True
MAV_MODE_FLAG_CUSTOM_MODE_ENABLED = 1
enums["MAV_MODE_FLAG"][1] = EnumEntry("MAV_MODE_FLAG_CUSTOM_MODE_ENABLED", """0b00000001 system has a custom mode active.""")
MAV_MODE_FLAG_GUIDED_ENABLED = 4
enums["MAV_MODE_FLAG"][4] = EnumEntry("MAV_MODE_FLAG_GUIDED_ENABLED", """0b00000100 guided mode enabled, system flies waypoints / mission items.""")
MAV_MODE_FLAG_MANUAL_INPUT_ENABLED = 64
enums["MAV_MODE_FLAG"][64] = EnumEntry("MAV_MODE_FLAG_MANUAL_INPUT_ENABLED", """0b01000000 remote control input is enabled.""")
MAV_MODE_FLAG_SAFETY_ARMED = 128
enums["MAV_MODE_FLAG"][128] = EnumEntry("MAV_MODE_FLAG_SAFETY_ARMED", """0b10000000 MAV safety set to armed.""")
MAV_MODE_FLAG_ENUM_END = 129
enums["MAV_MODE_FLAG"][129] = EnumEntry("MAV_MODE_FLAG_ENUM_END", """""")

# MAV_STATE
enums["MAV_STATE"] = Enum()
enums["MAV_STATE"].bitmask = False
MAV_STATE_UNINIT = 0
enums["MAV_STATE"][0] = EnumEntry("MAV_STATE_UNINIT", """Uninitialized system.""")
MAV_STATE_BOOT = 1
enums["MAV_STATE"][1] = EnumEntry("MAV_STATE_BOOT", """System is booting up.""")
MAV_STATE_CALIBRATING = 2
enums["MAV_STATE"][2] = EnumEntry("MAV_STATE_CALIBRATING", """System is calibrating.""")
MAV_STATE_STANDBY = 3
enums["MAV_STATE"][3] = EnumEntry("MAV_STATE_STANDBY", """System is grounded and on standby.""")
MAV_STATE_ACTIVE = 4
enums["MAV_STATE"][4] = EnumEntry("MAV_STATE_ACTIVE", """System is active and might be already airborne.""")
MAV_STATE_CRITICAL = 5
enums["MAV_STATE"][5] = EnumEntry("MAV_STATE_CRITICAL", """System is in a non-normal flight mode.""")
MAV_STATE_EMERGENCY = 6
enums["MAV_STATE"][6] = EnumEntry("MAV_STATE_EMERGENCY", """System is in a non-normal flight mode – it lost control over parts or over the whole airframe.""")
MAV_STATE_ENUM_END = 7
enums["MAV_STATE"][7] = EnumEntry("MAV_STATE_ENUM_END", """""")

# MAV_FRAME
enums["MAV_FRAME"] = Enum()
enums["MAV_FRAME"].bitmask = False
MAV_FRAME_LOCAL_NED = 1
enums["MAV_FRAME"][1] = EnumEntry("MAV_FRAME_LOCAL_NED", """NED local tangent frame (x: north, y: east, z: down).""")
MAV_FRAME_LOCAL_OFFSET_NED = 7
enums["MAV_FRAME"][7] = EnumEntry("MAV_FRAME_LOCAL_OFFSET_NED", """NED local tangent frame, offset from vehicle position.""")
MAV_FRAME_BODY_NED = 8
enums["MAV_FRAME"][8] = EnumEntry("MAV_FRAME_BODY_NED", """Same as MAV_FRAME_LOCAL_NED rotated 90 degrees clockwise around z-axis.""")
MAV_FRAME_BODY_OFFSET_NED = 9
enums["MAV_FRAME"][9] = EnumEntry("MAV_FRAME_BODY_OFFSET_NED", """Offset in body frame, rotated.""")
MAV_FRAME_ENUM_END = 10
enums["MAV_FRAME"][10] = EnumEntry("MAV_FRAME_ENUM_END", """""")

# POSITION_TARGET_TYPEMASK
enums["POSITION_TARGET_TYPEMASK"] = Enum()
enums["POSITION_TARGET_TYPEMASK"].bitmask = True
POSITION_TARGET_TYPEMASK_X_IGNORE = 1
enums["POSITION_TARGET_TYPEMASK"][1] = EnumEntry("POSITION_TARGET_TYPEMASK_X_IGNORE", """Ignore position x.""")
POSITION_TARGET_TYPEMASK_Y_IGNORE = 2
enums["POSITION_TARGET_TYPEMASK"][2] = EnumEntry("POSITION_TARGET_TYPEMASK_Y_IGNORE", """Ignore position y.""")
POSITION_TARGET_TYPEMASK_Z_IGNORE = 4
enums["POSITION_TARGET_TYPEMASK"][4] = EnumEntry("POSITION_TARGET_TYPEMASK_Z_IGNORE", """Ignore position z.""")
POSITION_TARGET_TYPEMASK_VX_IGNORE = 8
enums["POSITION_TARGET_TYPEMASK"][8] = EnumEntry("POSITION_TARGET_TYPEMASK_VX_IGNORE", """Ignore velocity x.""")
POSITION_TARGET_TYPEMASK_VY_IGNORE = 16
enums["POSITION_TARGET_TYPEMASK"][16] = EnumEntry("POSITION_TARGET_TYPEMASK_VY_IGNORE", """Ignore velocity y.""")
POSITION_TARGET_TYPEMASK_VZ_IGNORE = 32
enums["POSITION_TARGET_TYPEMASK"][32] = EnumEntry("POSITION_TARGET_TYPEMASK_VZ_IGNORE", """Ignore velocity z.""")
POSITION_TARGET_TYPEMASK_AX_IGNORE = 64
enums["POSITION_TARGET_TYPEMASK"][64] = EnumEntry("POSITION_TARGET_TYPEMASK_AX_IGNORE", """Ignore acceleration x.""")
POSITION_TARGET_TYPEMASK_AY_IGNORE = 128
enums["POSITION_TARGET_TYPEMASK"][128] = EnumEntry("POSITION_TARGET_TYPEMASK_AY_IGNORE", """Ignore acceleration y.""")
POSITION_TARGET_TYPEMASK_AZ_IGNORE = 256
enums["POSITION_TARGET_TYPEMASK"][256] = EnumEntry("POSITION_TARGET_TYPEMASK_AZ_IGNORE", """Ignore acceleration z.""")
POSITION_TARGET_TYPEMASK_FORCE_SET = 512
enums["POSITION_TARGET_TYPEMASK"][512] = EnumEntry("POSITION_TARGET_TYPEMASK_FORCE_SET", """Use force instead of acceleration.""")
POSITION_TARGET_TYPEMASK_YAW_IGNORE = 1024
enums["POSITION_TARGET_TYPEMASK"][1024] = EnumEntry("POSITION_TARGET_TYPEMASK_YAW_IGNORE", """Ignore yaw.""")
POSITION_TARGET_TYPEMASK_YAW_RATE_IGNORE = 2048
enums["POSITION_TARGET_TYPEMASK"][2048] = EnumEntry("POSITION_TARGET_TYPEMASK_YAW_RATE_IGNORE", """Ignore yaw rate.""")
POSITION_TARGET_TYPEMASK_ENUM_END = 2049
enums["POSITION_TARGET_TYPEMASK"][2049] = EnumEntry("POSITION_TARGET_TYPEMASK_ENUM_END", """""")

# ATTITUDE_TARGET_TYPEMASK
enums["ATTITUDE_TARGET_TYPEMASK"] = Enum()
enums["ATTITUDE_TARGET_TYPEMASK"].bitmask = True
ATTITUDE_TARGET_TYPEMASK_BODY_ROLL_RATE_IGNORE = 1
enums["ATTITUDE_TARGET_TYPEMASK"][1] = EnumEntry("ATTITUDE_TARGET_TYPEMASK_BODY_ROLL_RATE_IGNORE", """Ignore roll rate.""")
ATTITUDE_TARGET_TYPEMASK_BODY_PITCH_RATE_IGNORE = 2
enums["ATTITUDE_TARGET_TYPEMASK"][2] = EnumEntry("ATTITUDE_TARGET_TYPEMASK_BODY_PITCH_RATE_IGNORE", """Ignore pitch rate.""")
ATTITUDE_TARGET_TYPEMASK_BODY_YAW_RATE_IGNORE = 4
enums["ATTITUDE_TARGET_TYPEMASK"][4] = EnumEntry("ATTITUDE_TARGET_TYPEMASK_BODY_YAW_RATE_IGNORE", """Ignore yaw rate.""")
ATTITUDE_TARGET_TYPEMASK_THRUST_BODY_SET = 32
enums["ATTITUDE_TARGET_TYPEMASK"][32] = EnumEntry("ATTITUDE_TARGET_TYPEMASK_THRUST_BODY_SET", """Use 3D body thrust setpoint instead of throttle.""")
ATTITUDE_TARGET_TYPEMASK_THROTTLE_IGNORE = 64
enums["ATTITUDE_TARGET_TYPEMASK"][64] = EnumEntry("ATTITUDE_TARGET_TYPEMASK_THROTTLE_IGNORE", """Ignore throttle.""")
ATTITUDE_TARGET_TYPEMASK_ATTITUDE_IGNORE = 128
enums["ATTITUDE_TARGET_TYPEMASK"][128] = EnumEntry("ATTITUDE_TARGET_TYPEMASK_ATTITUDE_IGNORE", """Ignore attitude.""")
ATTITUDE_TARGET_TYPEMASK_ENUM_END = 129
enums["ATTITUDE_TARGET_TYPEMASK"][129] = EnumEntry("ATTITUDE_TARGET_TYPEMASK_ENUM_END", """""")

# MAV_ESTIMATOR_TYPE
enums["MAV_ESTIMATOR_TYPE"] = Enum()
enums["MAV_ESTIMATOR_TYPE"].bitmask = False
MAV_ESTIMATOR_TYPE_UNKNOWN = 0
enums["MAV_ESTIMATOR_TYPE"][0] = EnumEntry("MAV_ESTIMATOR_TYPE_UNKNOWN", """Unknown type of the estimator.""")
MAV_ESTIMATOR_TYPE_NAIVE = 1
enums["MAV_ESTIMATOR_TYPE"][1] = EnumEntry("MAV_ESTIMATOR_TYPE_NAIVE", """This is a naive estimator without any real covariance feedback.""")
MAV_ESTIMATOR_TYPE_VISION = 2
enums["MAV_ESTIMATOR_TYPE"][2] = EnumEntry("MAV_ESTIMATOR_TYPE_VISION", """Computer vision based estimate.""")
MAV_ESTIMATOR_TYPE_VIO = 3
enums["MAV_ESTIMATOR_TYPE"][3] = EnumEntry("MAV_ESTIMATOR_TYPE_VIO", """Visual-inertial estimate.""")
MAV_ESTIMATOR_TYPE_GPS = 4
enums["MAV_ESTIMATOR_TYPE"][4] = EnumEntry("MAV_ESTIMATOR_TYPE_GPS", """Plain GPS estimate.""")
MAV_ESTIMATOR_TYPE_GPS_INS = 5
enums["MAV_ESTIMATOR_TYPE"][5] = EnumEntry("MAV_ESTIMATOR_TYPE_GPS_INS", """Estimator integrating GPS and inertial sensing.""")
MAV_ESTIMATOR_TYPE_MOCAP = 6
enums["MAV_ESTIMATOR_TYPE"][6] = EnumEntry("MAV_ESTIMATOR_TYPE_MOCAP", """Estimate from external motion capturing system.""")
MAV_ESTIMATOR_TYPE_LIDAR = 7
enums["MAV_ESTIMATOR_TYPE"][7] = EnumEntry("MAV_ESTIMATOR_TYPE_LIDAR", """Estimator based on lidar sensor input.""")
MAV_ESTIMATOR_TYPE_AUTOPILOT = 8
enums["MAV_ESTIMATOR_TYPE"][8] = EnumEntry("MAV_ESTIMATOR_TYPE_AUTOPILOT", """Estimator on autopilot.""")
MAV_ESTIMATOR_TYPE_ENUM_END = 9
enums["MAV_ESTIMATOR_TYPE"][9] = EnumEntry("MAV_ESTIMATOR_TYPE_ENUM_END", """""")

# message IDs
MAVLINK_MSG_ID_BAD_DATA = -1
MAVLINK_MSG_ID_UNKNOWN = -2
MAVLINK_MSG_ID_HEARTBEAT = 0
MAVLINK_MSG_ID_ATTITUDE = 30
MAVLINK_MSG_ID_SET_ATTITUDE_TARGET = 82
MAVLINK_MSG_ID_SET_POSITION_TARGET_LOCAL_NED = 84
MAVLINK_MSG_ID_HIGHRES_IMU = 105
MAVLINK_MSG_ID_TIMESYNC = 111
MAVLINK_MSG_ID_ODOMETRY = 331


class MAVLink_heartbeat_message(MAVLink_message):
    """
    The heartbeat message shows that a system or component is present
    and responding.         Emitted by the simulator at 1 Hz to allow
    the client to detect connection loss.
    """

    id = MAVLINK_MSG_ID_HEARTBEAT
    msgname = "HEARTBEAT"
    fieldnames = ["custom_mode", "type", "autopilot", "base_mode", "system_status", "mavlink_version"]
    ordered_fieldnames = ["custom_mode", "type", "autopilot", "base_mode", "system_status", "mavlink_version"]
    fieldtypes = ["uint32_t", "uint8_t", "uint8_t", "uint8_t", "uint8_t", "uint8_t"]
    fielddisplays_by_name: Dict[str, str] = {"base_mode": "bitmask"}
    fieldenums_by_name: Dict[str, str] = {"type": "MAV_TYPE", "autopilot": "MAV_AUTOPILOT", "base_mode": "MAV_MODE_FLAG", "system_status": "MAV_STATE"}
    fieldunits_by_name: Dict[str, str] = {}
    native_format = bytearray(b"<IBBBBB")
    orders = [0, 1, 2, 3, 4, 5]
    lengths = [1, 1, 1, 1, 1, 1]
    array_lengths = [0, 0, 0, 0, 0, 0]
    crc_extra = 50
    unpacker = struct.Struct("<IBBBBB")
    instance_field = None
    instance_offset = -1

    def __init__(self, custom_mode: int, type: int, autopilot: int, base_mode: int, system_status: int, mavlink_version: int):
        MAVLink_message.__init__(self, MAVLink_heartbeat_message.id, MAVLink_heartbeat_message.msgname)
        self._fieldnames = MAVLink_heartbeat_message.fieldnames
        self._instance_field = MAVLink_heartbeat_message.instance_field
        self._instance_offset = MAVLink_heartbeat_message.instance_offset
        self.custom_mode = custom_mode
        self.type = type
        self.autopilot = autopilot
        self.base_mode = base_mode
        self.system_status = system_status
        self.mavlink_version = mavlink_version

    def pack(self, mav: "MAVLink", force_mavlink1: bool = False) -> bytes:
        return self._pack(mav, self.crc_extra, self.unpacker.pack(self.custom_mode, self.type, self.autopilot, self.base_mode, self.system_status, self.mavlink_version), force_mavlink1=force_mavlink1)


# Define name on the class for backwards compatibility (it is now msgname).
# Done with setattr to hide the class variable from mypy.
setattr(MAVLink_heartbeat_message, "name", mavlink_msg_deprecated_name_property())


class MAVLink_attitude_message(MAVLink_message):
    """
    The attitude in the aeronautical frame (right-hand, Z-down /
    x-front, y-right).         Sent by the simulator to convey current
    vehicle orientation and angular rates.
    """

    id = MAVLINK_MSG_ID_ATTITUDE
    msgname = "ATTITUDE"
    fieldnames = ["time_boot_ms", "roll", "pitch", "yaw", "rollspeed", "pitchspeed", "yawspeed"]
    ordered_fieldnames = ["time_boot_ms", "roll", "pitch", "yaw", "rollspeed", "pitchspeed", "yawspeed"]
    fieldtypes = ["uint32_t", "float", "float", "float", "float", "float", "float"]
    fielddisplays_by_name: Dict[str, str] = {}
    fieldenums_by_name: Dict[str, str] = {}
    fieldunits_by_name: Dict[str, str] = {"time_boot_ms": "ms", "roll": "rad", "pitch": "rad", "yaw": "rad", "rollspeed": "rad/s", "pitchspeed": "rad/s", "yawspeed": "rad/s"}
    native_format = bytearray(b"<Iffffff")
    orders = [0, 1, 2, 3, 4, 5, 6]
    lengths = [1, 1, 1, 1, 1, 1, 1]
    array_lengths = [0, 0, 0, 0, 0, 0, 0]
    crc_extra = 39
    unpacker = struct.Struct("<Iffffff")
    instance_field = None
    instance_offset = -1

    def __init__(self, time_boot_ms: int, roll: float, pitch: float, yaw: float, rollspeed: float, pitchspeed: float, yawspeed: float):
        MAVLink_message.__init__(self, MAVLink_attitude_message.id, MAVLink_attitude_message.msgname)
        self._fieldnames = MAVLink_attitude_message.fieldnames
        self._instance_field = MAVLink_attitude_message.instance_field
        self._instance_offset = MAVLink_attitude_message.instance_offset
        self.time_boot_ms = time_boot_ms
        self.roll = roll
        self.pitch = pitch
        self.yaw = yaw
        self.rollspeed = rollspeed
        self.pitchspeed = pitchspeed
        self.yawspeed = yawspeed

    def pack(self, mav: "MAVLink", force_mavlink1: bool = False) -> bytes:
        return self._pack(mav, self.crc_extra, self.unpacker.pack(self.time_boot_ms, self.roll, self.pitch, self.yaw, self.rollspeed, self.pitchspeed, self.yawspeed), force_mavlink1=force_mavlink1)


# Define name on the class for backwards compatibility (it is now msgname).
# Done with setattr to hide the class variable from mypy.
setattr(MAVLink_attitude_message, "name", mavlink_msg_deprecated_name_property())


class MAVLink_set_attitude_target_message(MAVLink_message):
    """
    Sets a desired vehicle attitude. Used by the contestant control
    software to         command the simulator. The type_mask field
    selects which sub-fields are active.
    """

    id = MAVLINK_MSG_ID_SET_ATTITUDE_TARGET
    msgname = "SET_ATTITUDE_TARGET"
    fieldnames = ["time_boot_ms", "target_system", "target_component", "type_mask", "q", "body_roll_rate", "body_pitch_rate", "body_yaw_rate", "thrust"]
    ordered_fieldnames = ["time_boot_ms", "q", "body_roll_rate", "body_pitch_rate", "body_yaw_rate", "thrust", "target_system", "target_component", "type_mask"]
    fieldtypes = ["uint32_t", "uint8_t", "uint8_t", "uint8_t", "float", "float", "float", "float", "float"]
    fielddisplays_by_name: Dict[str, str] = {"type_mask": "bitmask"}
    fieldenums_by_name: Dict[str, str] = {"type_mask": "ATTITUDE_TARGET_TYPEMASK"}
    fieldunits_by_name: Dict[str, str] = {"time_boot_ms": "ms", "body_roll_rate": "rad/s", "body_pitch_rate": "rad/s", "body_yaw_rate": "rad/s"}
    native_format = bytearray(b"<IfffffBBB")
    orders = [0, 6, 7, 8, 1, 2, 3, 4, 5]
    lengths = [1, 4, 1, 1, 1, 1, 1, 1, 1]
    array_lengths = [0, 4, 0, 0, 0, 0, 0, 0, 0]
    crc_extra = 49
    unpacker = struct.Struct("<I4fffffBBB")
    instance_field = None
    instance_offset = -1

    def __init__(self, time_boot_ms: int, target_system: int, target_component: int, type_mask: int, q: Sequence[float], body_roll_rate: float, body_pitch_rate: float, body_yaw_rate: float, thrust: float):
        MAVLink_message.__init__(self, MAVLink_set_attitude_target_message.id, MAVLink_set_attitude_target_message.msgname)
        self._fieldnames = MAVLink_set_attitude_target_message.fieldnames
        self._instance_field = MAVLink_set_attitude_target_message.instance_field
        self._instance_offset = MAVLink_set_attitude_target_message.instance_offset
        self.time_boot_ms = time_boot_ms
        self.target_system = target_system
        self.target_component = target_component
        self.type_mask = type_mask
        self.q = q
        self.body_roll_rate = body_roll_rate
        self.body_pitch_rate = body_pitch_rate
        self.body_yaw_rate = body_yaw_rate
        self.thrust = thrust

    def pack(self, mav: "MAVLink", force_mavlink1: bool = False) -> bytes:
        return self._pack(mav, self.crc_extra, self.unpacker.pack(self.time_boot_ms, self.q[0], self.q[1], self.q[2], self.q[3], self.body_roll_rate, self.body_pitch_rate, self.body_yaw_rate, self.thrust, self.target_system, self.target_component, self.type_mask), force_mavlink1=force_mavlink1)


# Define name on the class for backwards compatibility (it is now msgname).
# Done with setattr to hide the class variable from mypy.
setattr(MAVLink_set_attitude_target_message, "name", mavlink_msg_deprecated_name_property())


class MAVLink_set_position_target_local_ned_message(MAVLink_message):
    """
    Sets a desired vehicle position in a local north-east-down
    coordinate frame.         Used by the contestant control software
    to send position / velocity / acceleration         setpoints to
    the simulator. Use type_mask to ignore sub-fields.
    """

    id = MAVLINK_MSG_ID_SET_POSITION_TARGET_LOCAL_NED
    msgname = "SET_POSITION_TARGET_LOCAL_NED"
    fieldnames = ["time_boot_ms", "target_system", "target_component", "coordinate_frame", "type_mask", "x", "y", "z", "vx", "vy", "vz", "afx", "afy", "afz", "yaw", "yaw_rate"]
    ordered_fieldnames = ["time_boot_ms", "x", "y", "z", "vx", "vy", "vz", "afx", "afy", "afz", "yaw", "yaw_rate", "type_mask", "target_system", "target_component", "coordinate_frame"]
    fieldtypes = ["uint32_t", "uint8_t", "uint8_t", "uint8_t", "uint16_t", "float", "float", "float", "float", "float", "float", "float", "float", "float", "float", "float"]
    fielddisplays_by_name: Dict[str, str] = {"type_mask": "bitmask"}
    fieldenums_by_name: Dict[str, str] = {"coordinate_frame": "MAV_FRAME", "type_mask": "POSITION_TARGET_TYPEMASK"}
    fieldunits_by_name: Dict[str, str] = {"time_boot_ms": "ms", "x": "m", "y": "m", "z": "m", "vx": "m/s", "vy": "m/s", "vz": "m/s", "afx": "m/s/s", "afy": "m/s/s", "afz": "m/s/s", "yaw": "rad", "yaw_rate": "rad/s"}
    native_format = bytearray(b"<IfffffffffffHBBB")
    orders = [0, 13, 14, 15, 12, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11]
    lengths = [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1]
    array_lengths = [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
    crc_extra = 143
    unpacker = struct.Struct("<IfffffffffffHBBB")
    instance_field = None
    instance_offset = -1

    def __init__(self, time_boot_ms: int, target_system: int, target_component: int, coordinate_frame: int, type_mask: int, x: float, y: float, z: float, vx: float, vy: float, vz: float, afx: float, afy: float, afz: float, yaw: float, yaw_rate: float):
        MAVLink_message.__init__(self, MAVLink_set_position_target_local_ned_message.id, MAVLink_set_position_target_local_ned_message.msgname)
        self._fieldnames = MAVLink_set_position_target_local_ned_message.fieldnames
        self._instance_field = MAVLink_set_position_target_local_ned_message.instance_field
        self._instance_offset = MAVLink_set_position_target_local_ned_message.instance_offset
        self.time_boot_ms = time_boot_ms
        self.target_system = target_system
        self.target_component = target_component
        self.coordinate_frame = coordinate_frame
        self.type_mask = type_mask
        self.x = x
        self.y = y
        self.z = z
        self.vx = vx
        self.vy = vy
        self.vz = vz
        self.afx = afx
        self.afy = afy
        self.afz = afz
        self.yaw = yaw
        self.yaw_rate = yaw_rate

    def pack(self, mav: "MAVLink", force_mavlink1: bool = False) -> bytes:
        return self._pack(mav, self.crc_extra, self.unpacker.pack(self.time_boot_ms, self.x, self.y, self.z, self.vx, self.vy, self.vz, self.afx, self.afy, self.afz, self.yaw, self.yaw_rate, self.type_mask, self.target_system, self.target_component, self.coordinate_frame), force_mavlink1=force_mavlink1)


# Define name on the class for backwards compatibility (it is now msgname).
# Done with setattr to hide the class variable from mypy.
setattr(MAVLink_set_position_target_local_ned_message, "name", mavlink_msg_deprecated_name_property())


class MAVLink_highres_imu_message(MAVLink_message):
    """
    The IMU readings in SI units in NED body frame.         Sent by
    the simulator to convey current vehicle sensor state.
    """

    id = MAVLINK_MSG_ID_HIGHRES_IMU
    msgname = "HIGHRES_IMU"
    fieldnames = ["time_usec", "xacc", "yacc", "zacc", "xgyro", "ygyro", "zgyro", "xmag", "ymag", "zmag", "abs_pressure", "diff_pressure", "pressure_alt", "temperature", "fields_updated", "id"]
    ordered_fieldnames = ["time_usec", "xacc", "yacc", "zacc", "xgyro", "ygyro", "zgyro", "xmag", "ymag", "zmag", "abs_pressure", "diff_pressure", "pressure_alt", "temperature", "fields_updated", "id"]
    fieldtypes = ["uint64_t", "float", "float", "float", "float", "float", "float", "float", "float", "float", "float", "float", "float", "float", "uint16_t", "uint8_t"]
    fielddisplays_by_name: Dict[str, str] = {"fields_updated": "bitmask"}
    fieldenums_by_name: Dict[str, str] = {}
    fieldunits_by_name: Dict[str, str] = {"time_usec": "us", "xacc": "m/s/s", "yacc": "m/s/s", "zacc": "m/s/s", "xgyro": "rad/s", "ygyro": "rad/s", "zgyro": "rad/s", "xmag": "gauss", "ymag": "gauss", "zmag": "gauss", "abs_pressure": "hPa", "diff_pressure": "hPa", "pressure_alt": "m", "temperature": "degC"}
    native_format = bytearray(b"<QfffffffffffffHB")
    orders = [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15]
    lengths = [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1]
    array_lengths = [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
    crc_extra = 253
    unpacker = struct.Struct("<QfffffffffffffHB")
    instance_field = None
    instance_offset = -1

    def __init__(self, time_usec: int, xacc: float, yacc: float, zacc: float, xgyro: float, ygyro: float, zgyro: float, xmag: float, ymag: float, zmag: float, abs_pressure: float, diff_pressure: float, pressure_alt: float, temperature: float, fields_updated: int, id: int):
        MAVLink_message.__init__(self, MAVLink_highres_imu_message.id, MAVLink_highres_imu_message.msgname)
        self._fieldnames = MAVLink_highres_imu_message.fieldnames
        self._instance_field = MAVLink_highres_imu_message.instance_field
        self._instance_offset = MAVLink_highres_imu_message.instance_offset
        self.time_usec = time_usec
        self.xacc = xacc
        self.yacc = yacc
        self.zacc = zacc
        self.xgyro = xgyro
        self.ygyro = ygyro
        self.zgyro = zgyro
        self.xmag = xmag
        self.ymag = ymag
        self.zmag = zmag
        self.abs_pressure = abs_pressure
        self.diff_pressure = diff_pressure
        self.pressure_alt = pressure_alt
        self.temperature = temperature
        self.fields_updated = fields_updated
        self.id = id

    def pack(self, mav: "MAVLink", force_mavlink1: bool = False) -> bytes:
        return self._pack(mav, self.crc_extra, self.unpacker.pack(self.time_usec, self.xacc, self.yacc, self.zacc, self.xgyro, self.ygyro, self.zgyro, self.xmag, self.ymag, self.zmag, self.abs_pressure, self.diff_pressure, self.pressure_alt, self.temperature, self.fields_updated, self.id), force_mavlink1=force_mavlink1)


# Define name on the class for backwards compatibility (it is now msgname).
# Done with setattr to hide the class variable from mypy.
setattr(MAVLink_highres_imu_message, "name", mavlink_msg_deprecated_name_property())


class MAVLink_timesync_message(MAVLink_message):
    """
    Time synchronisation message. The simulator sends this with tc1=0
    to initiate         a sync request. The client echoes it back with
    tc1 set to the current timestamp,         allowing the simulator
    to compute clock offset. Both sides repeat the exchange
    periodically (recommended: every 5 s).
    """

    id = MAVLINK_MSG_ID_TIMESYNC
    msgname = "TIMESYNC"
    fieldnames = ["tc1", "ts1"]
    ordered_fieldnames = ["tc1", "ts1"]
    fieldtypes = ["int64_t", "int64_t"]
    fielddisplays_by_name: Dict[str, str] = {}
    fieldenums_by_name: Dict[str, str] = {}
    fieldunits_by_name: Dict[str, str] = {"tc1": "ns", "ts1": "ns"}
    native_format = bytearray(b"<qq")
    orders = [0, 1]
    lengths = [1, 1]
    array_lengths = [0, 0]
    crc_extra = 34
    unpacker = struct.Struct("<qq")
    instance_field = None
    instance_offset = -1

    def __init__(self, tc1: int, ts1: int):
        MAVLink_message.__init__(self, MAVLink_timesync_message.id, MAVLink_timesync_message.msgname)
        self._fieldnames = MAVLink_timesync_message.fieldnames
        self._instance_field = MAVLink_timesync_message.instance_field
        self._instance_offset = MAVLink_timesync_message.instance_offset
        self.tc1 = tc1
        self.ts1 = ts1

    def pack(self, mav: "MAVLink", force_mavlink1: bool = False) -> bytes:
        return self._pack(mav, self.crc_extra, self.unpacker.pack(self.tc1, self.ts1), force_mavlink1=force_mavlink1)


# Define name on the class for backwards compatibility (it is now msgname).
# Done with setattr to hide the class variable from mypy.
setattr(MAVLink_timesync_message, "name", mavlink_msg_deprecated_name_property())


class MAVLink_odometry_message(MAVLink_message):
    """
    Odometry message encoding the position and velocity in a given
    reference frame.         Sent by the simulator to provide ground-
    truth or estimated state for the vehicle.
    """

    id = MAVLINK_MSG_ID_ODOMETRY
    msgname = "ODOMETRY"
    fieldnames = ["time_usec", "frame_id", "child_frame_id", "x", "y", "z", "q", "vx", "vy", "vz", "rollspeed", "pitchspeed", "yawspeed", "pose_covariance", "velocity_covariance", "reset_counter", "estimator_type"]
    ordered_fieldnames = ["time_usec", "x", "y", "z", "q", "vx", "vy", "vz", "rollspeed", "pitchspeed", "yawspeed", "pose_covariance", "velocity_covariance", "frame_id", "child_frame_id", "reset_counter", "estimator_type"]
    fieldtypes = ["uint64_t", "uint8_t", "uint8_t", "float", "float", "float", "float", "float", "float", "float", "float", "float", "float", "float", "float", "uint8_t", "int8_t"]
    fielddisplays_by_name: Dict[str, str] = {}
    fieldenums_by_name: Dict[str, str] = {"frame_id": "MAV_FRAME", "child_frame_id": "MAV_FRAME", "estimator_type": "MAV_ESTIMATOR_TYPE"}
    fieldunits_by_name: Dict[str, str] = {"time_usec": "us", "x": "m", "y": "m", "z": "m", "vx": "m/s", "vy": "m/s", "vz": "m/s", "rollspeed": "rad/s", "pitchspeed": "rad/s", "yawspeed": "rad/s"}
    native_format = bytearray(b"<QffffffffffffBBBb")
    orders = [0, 13, 14, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 15, 16]
    lengths = [1, 1, 1, 1, 4, 1, 1, 1, 1, 1, 1, 21, 21, 1, 1, 1, 1]
    array_lengths = [0, 0, 0, 0, 4, 0, 0, 0, 0, 0, 0, 21, 21, 0, 0, 0, 0]
    crc_extra = 243
    unpacker = struct.Struct("<Qfff4fffffff21f21fBBBb")
    instance_field = None
    instance_offset = -1

    def __init__(self, time_usec: int, frame_id: int, child_frame_id: int, x: float, y: float, z: float, q: Sequence[float], vx: float, vy: float, vz: float, rollspeed: float, pitchspeed: float, yawspeed: float, pose_covariance: Sequence[float], velocity_covariance: Sequence[float], reset_counter: int, estimator_type: int):
        MAVLink_message.__init__(self, MAVLink_odometry_message.id, MAVLink_odometry_message.msgname)
        self._fieldnames = MAVLink_odometry_message.fieldnames
        self._instance_field = MAVLink_odometry_message.instance_field
        self._instance_offset = MAVLink_odometry_message.instance_offset
        self.time_usec = time_usec
        self.frame_id = frame_id
        self.child_frame_id = child_frame_id
        self.x = x
        self.y = y
        self.z = z
        self.q = q
        self.vx = vx
        self.vy = vy
        self.vz = vz
        self.rollspeed = rollspeed
        self.pitchspeed = pitchspeed
        self.yawspeed = yawspeed
        self.pose_covariance = pose_covariance
        self.velocity_covariance = velocity_covariance
        self.reset_counter = reset_counter
        self.estimator_type = estimator_type

    def pack(self, mav: "MAVLink", force_mavlink1: bool = False) -> bytes:
        return self._pack(mav, self.crc_extra, self.unpacker.pack(self.time_usec, self.x, self.y, self.z, self.q[0], self.q[1], self.q[2], self.q[3], self.vx, self.vy, self.vz, self.rollspeed, self.pitchspeed, self.yawspeed, self.pose_covariance[0], self.pose_covariance[1], self.pose_covariance[2], self.pose_covariance[3], self.pose_covariance[4], self.pose_covariance[5], self.pose_covariance[6], self.pose_covariance[7], self.pose_covariance[8], self.pose_covariance[9], self.pose_covariance[10], self.pose_covariance[11], self.pose_covariance[12], self.pose_covariance[13], self.pose_covariance[14], self.pose_covariance[15], self.pose_covariance[16], self.pose_covariance[17], self.pose_covariance[18], self.pose_covariance[19], self.pose_covariance[20], self.velocity_covariance[0], self.velocity_covariance[1], self.velocity_covariance[2], self.velocity_covariance[3], self.velocity_covariance[4], self.velocity_covariance[5], self.velocity_covariance[6], self.velocity_covariance[7], self.velocity_covariance[8], self.velocity_covariance[9], self.velocity_covariance[10], self.velocity_covariance[11], self.velocity_covariance[12], self.velocity_covariance[13], self.velocity_covariance[14], self.velocity_covariance[15], self.velocity_covariance[16], self.velocity_covariance[17], self.velocity_covariance[18], self.velocity_covariance[19], self.velocity_covariance[20], self.frame_id, self.child_frame_id, self.reset_counter, self.estimator_type), force_mavlink1=force_mavlink1)


# Define name on the class for backwards compatibility (it is now msgname).
# Done with setattr to hide the class variable from mypy.
setattr(MAVLink_odometry_message, "name", mavlink_msg_deprecated_name_property())


mavlink_map: Dict[int, Type[MAVLink_message]] = {
    MAVLINK_MSG_ID_HEARTBEAT: MAVLink_heartbeat_message,
    MAVLINK_MSG_ID_ATTITUDE: MAVLink_attitude_message,
    MAVLINK_MSG_ID_SET_ATTITUDE_TARGET: MAVLink_set_attitude_target_message,
    MAVLINK_MSG_ID_SET_POSITION_TARGET_LOCAL_NED: MAVLink_set_position_target_local_ned_message,
    MAVLINK_MSG_ID_HIGHRES_IMU: MAVLink_highres_imu_message,
    MAVLINK_MSG_ID_TIMESYNC: MAVLink_timesync_message,
    MAVLINK_MSG_ID_ODOMETRY: MAVLink_odometry_message,
}


class MAVError(Exception):
    """MAVLink error class"""

    def __init__(self, msg: str) -> None:
        Exception.__init__(self, msg)
        self.message = msg


class MAVLink_bad_data(MAVLink_message):
    """
    a piece of bad data in a mavlink stream
    """

    def __init__(self, data: bytes, reason: str) -> None:
        MAVLink_message.__init__(self, MAVLINK_MSG_ID_BAD_DATA, "BAD_DATA")
        self._fieldnames = ["data", "reason"]
        self.data = data
        self.reason = reason
        self._msgbuf = bytearray(data)
        self._instance_field = None

    def __str__(self) -> str:
        """Override the __str__ function from MAVLink_messages because non-printable characters are common in to be the reason for this message to exist."""
        hexstr = ["{:x}".format(i) for i in self.data]
        return "%s {%s, data:%s}" % (self._type, self.reason, hexstr)


class MAVLink_unknown(MAVLink_message):
    """
    a message that we don't have in the XML used when built
    """

    def __init__(self, msgid: int, data: bytes) -> None:
        MAVLink_message.__init__(self, MAVLINK_MSG_ID_UNKNOWN, "UNKNOWN_%u" % msgid)
        self._fieldnames = ["data"]
        self.data = data
        self._msgbuf = bytearray(data)
        self._instance_field = None

    def __str__(self) -> str:
        """Override the __str__ function from MAVLink_messages because non-printable characters are common."""
        hexstr = ["{:x}".format(i) for i in self.data]
        return "%s {data:%s}" % (self._type, hexstr)


class MAVLinkSigning(object):
    """MAVLink signing state class"""

    def __init__(self) -> None:
        self.secret_key: Optional[bytes] = None
        self.timestamp = 0
        self.link_id = 0
        self.sign_outgoing = False
        self.allow_unsigned_callback: Optional[Callable[["MAVLink", int], bool]] = None
        self.stream_timestamps: Dict[Tuple[int, int, int], int] = {}
        self.sig_count = 0
        self.badsig_count = 0
        self.goodsig_count = 0
        self.unsigned_count = 0
        self.reject_count = 0


MAVLinkV1Header = Tuple[bytes, int, int, int, int, int]
MAVLinkV2Header = Tuple[bytes, int, int, int, int, int, int, int, int]

class MAVLink(object):
    """MAVLink protocol handling class"""

    def __init__(self, file: Any, srcSystem: int = 0, srcComponent: int = 0, use_native: bool = False) -> None:
        self.seq = 0
        self.file = file
        self.srcSystem = srcSystem
        self.srcComponent = srcComponent
        self.callback: Optional[Callable[..., None]] = None
        self.callback_args: Optional[Iterable[Any]] = None
        self.callback_kwargs: Optional[Mapping[str, Any]] = None
        self.send_callback: Optional[Callable[..., None]] = None
        self.send_callback_args: Optional[Iterable[Any]] = None
        self.send_callback_kwargs: Optional[Mapping[str, Any]] = None
        self.buf = bytearray()
        self.buf_index = 0
        self.expected_length = HEADER_LEN_V1 + 2
        self.have_prefix_error = False
        self.robust_parsing = False
        self.protocol_marker = 253
        self.little_endian = True
        self.crc_extra = True
        self.sort_fields = True
        self.total_packets_sent = 0
        self.total_bytes_sent = 0
        self.total_packets_received = 0
        self.total_bytes_received = 0
        self.total_receive_errors = 0
        self.startup_time = time.time()
        self.signing = MAVLinkSigning()
        self.mav20_unpacker = struct.Struct("<cBBBBBBHB")
        self.mav10_unpacker = struct.Struct("<cBBBBB")
        self.mav20_h3_unpacker = struct.Struct("BBB")
        self.mav_csum_unpacker = struct.Struct("<H")
        self.mav_sign_unpacker = struct.Struct("<IH")

    def set_callback(self, callback: Callable[..., None], *args: Any, **kwargs: Any) -> None:
        self.callback = callback
        self.callback_args = args
        self.callback_kwargs = kwargs

    def set_send_callback(self, callback: Callable[..., None], *args: Any, **kwargs: Any) -> None:
        self.send_callback = callback
        self.send_callback_args = args
        self.send_callback_kwargs = kwargs

    def send(self, mavmsg: MAVLink_message, force_mavlink1: bool = False) -> None:
        """send a MAVLink message"""
        buf = mavmsg.pack(self, force_mavlink1=force_mavlink1)
        self.file.write(buf)
        self.seq = (self.seq + 1) % 256
        self.total_packets_sent += 1
        self.total_bytes_sent += len(buf)
        if self.send_callback is not None and self.send_callback_args is not None and self.send_callback_kwargs is not None:
            self.send_callback(mavmsg, *self.send_callback_args, **self.send_callback_kwargs)

    def buf_len(self) -> int:
        return len(self.buf) - self.buf_index

    def bytes_needed(self) -> int:
        """return number of bytes needed for next parsing stage"""
        ret = self.expected_length - self.buf_len()

        if ret <= 0:
            return 1
        return ret

    def __callbacks(self, msg: MAVLink_message) -> None:
        """this method exists only to make profiling results easier to read"""
        if self.callback is not None and self.callback_args is not None and self.callback_kwargs is not None:
            self.callback(msg, *self.callback_args, **self.callback_kwargs)

    def parse_char(self, c: Sequence[int]) -> Optional[MAVLink_message]:
        """input some data bytes, possibly returning a new message"""
        self.buf.extend(c)

        self.total_bytes_received += len(c)

        m = self.__parse_char_legacy()

        if m is not None:
            self.total_packets_received += 1
            self.__callbacks(m)
        else:
            # XXX The idea here is if we've read something and there's nothing left in
            # the buffer, reset it to 0 which frees the memory
            if self.buf_len() == 0 and self.buf_index != 0:
                self.buf = bytearray()
                self.buf_index = 0

        return m

    def __parse_char_legacy(self) -> Optional[MAVLink_message]:
        """input some data bytes, possibly returning a new message"""
        header_len = HEADER_LEN_V1
        if self.buf_len() >= 1 and self.buf[self.buf_index] == PROTOCOL_MARKER_V2:
            header_len = HEADER_LEN_V2

        m: Optional[MAVLink_message] = None
        if self.buf_len() >= 1 and self.buf[self.buf_index] != PROTOCOL_MARKER_V1 and self.buf[self.buf_index] != PROTOCOL_MARKER_V2:
            magic = self.buf[self.buf_index]
            self.buf_index += 1
            if self.robust_parsing:
                invalid_prefix_start = self.buf_index - 1
                while self.buf_len() >= 1 and self.buf[self.buf_index] != PROTOCOL_MARKER_V1 and self.buf[self.buf_index] != PROTOCOL_MARKER_V2:
                    self.buf_index += 1
                m = MAVLink_bad_data(self.buf[invalid_prefix_start : self.buf_index], "Bad prefix")
                self.expected_length = header_len + 2
                self.total_receive_errors += 1
                return m
            if self.have_prefix_error:
                return None
            self.have_prefix_error = True
            self.total_receive_errors += 1
            raise MAVError("invalid MAVLink prefix '%s'" % magic)
        self.have_prefix_error = False
        if self.buf_len() >= 3:
            sbuf = self.buf[self.buf_index : 3 + self.buf_index]
            unpacked_h3: Tuple[int, int, int] = self.mav20_h3_unpacker.unpack(sbuf)
            magic, self.expected_length, incompat_flags = unpacked_h3
            if magic == PROTOCOL_MARKER_V2 and (incompat_flags & MAVLINK_IFLAG_SIGNED):
                self.expected_length += MAVLINK_SIGNATURE_BLOCK_LEN
            self.expected_length += header_len + 2
        if self.expected_length >= (header_len + 2) and self.buf_len() >= self.expected_length:
            mbuf = self.buf[self.buf_index : self.buf_index + self.expected_length]
            self.buf_index += self.expected_length
            self.expected_length = header_len + 2
            if self.robust_parsing:
                try:
                    if magic == PROTOCOL_MARKER_V2 and (incompat_flags & ~MAVLINK_IFLAG_SIGNED) != 0:
                        raise MAVError("invalid incompat_flags 0x%x 0x%x %u" % (incompat_flags, magic, self.expected_length))
                    m = self.decode(mbuf)
                except MAVError as reason:
                    m = MAVLink_bad_data(mbuf, reason.message)
                    self.total_receive_errors += 1
            else:
                if magic == PROTOCOL_MARKER_V2 and (incompat_flags & ~MAVLINK_IFLAG_SIGNED) != 0:
                    raise MAVError("invalid incompat_flags 0x%x 0x%x %u" % (incompat_flags, magic, self.expected_length))
                m = self.decode(mbuf)
            return m
        return None

    def parse_buffer(self, s: Sequence[int]) -> Optional[List[MAVLink_message]]:
        """input some data bytes, possibly returning a list of new messages"""
        m = self.parse_char(s)
        if m is None:
            return None
        ret = [m]
        while True:
            m = self.parse_char(b"")
            if m is None:
                return ret
            ret.append(m)

    def check_signature(self, msgbuf: bytearray, srcSystem: int, srcComponent: int) -> bool:
        """check signature on incoming message"""
        assert self.signing.secret_key is not None

        timestamp_buf = msgbuf[-12:-6]
        link_id = msgbuf[-13]
        tbytes: Tuple[int, int] = self.mav_sign_unpacker.unpack(timestamp_buf)
        tlow, thigh = tbytes
        timestamp = tlow + (thigh << 32)

        # see if the timestamp is acceptable
        stream_key = (link_id, srcSystem, srcComponent)
        if stream_key in self.signing.stream_timestamps:
            if timestamp <= self.signing.stream_timestamps[stream_key]:
                # reject old timestamp
                logger.info("old timestamp")
                return False
        else:
            # a new stream has appeared. Accept the timestamp if it is at most
            # one minute behind our current timestamp
            if timestamp + 6000 * 1000 < self.signing.timestamp:
                logger.info("bad new stream %s %s", timestamp / (100.0 * 1000 * 60 * 60 * 24 * 365), self.signing.timestamp / (100.0 * 1000 * 60 * 60 * 24 * 365))
                return False
            logger.info("new stream")

        # set the streams timestamp so we reject timestamps that go backwards
        self.signing.stream_timestamps[stream_key] = timestamp

        h = hashlib.new("sha256")
        h.update(self.signing.secret_key)
        h.update(msgbuf[:-6])
        sig1 = h.digest()[:6]
        sig2 = msgbuf[-6:]
        if sig1 != sig2:
            logger.info("sig mismatch")
            return False

        # the timestamp we next send with is the max of the received timestamp and
        # our current timestamp
        self.signing.timestamp = max(self.signing.timestamp, timestamp)
        return True

    def decode(self, msgbuf: bytearray) -> MAVLink_message:
        """decode a buffer as a MAVLink message"""
        # decode the header
        if msgbuf[0] != PROTOCOL_MARKER_V1:
            headerlen = 10
            try:
                header_v2: MAVLinkV2Header = self.mav20_unpacker.unpack(msgbuf[:headerlen])
            except struct.error as emsg:
                raise MAVError("Unable to unpack MAVLink header: %s" % emsg)
            magic, mlen, incompat_flags, compat_flags, seq, srcSystem, srcComponent, msgIdlow, msgIdhigh = header_v2
            msgId = msgIdlow | (msgIdhigh << 16)
        else:
            headerlen = 6
            try:
                header_v1: MAVLinkV1Header = self.mav10_unpacker.unpack(msgbuf[:headerlen])
            except struct.error as emsg:
                raise MAVError("Unable to unpack MAVLink header: %s" % emsg)
            magic, mlen, seq, srcSystem, srcComponent, msgId = header_v1
            incompat_flags = 0
            compat_flags = 0
        mapkey = msgId
        if (incompat_flags & MAVLINK_IFLAG_SIGNED) != 0:
            signature_len = MAVLINK_SIGNATURE_BLOCK_LEN
        else:
            signature_len = 0

        if ord(magic) != PROTOCOL_MARKER_V1 and ord(magic) != PROTOCOL_MARKER_V2:
            raise MAVError("invalid MAVLink prefix '{}'".format(hex(ord(magic))))
        if mlen != len(msgbuf) - (headerlen + 2 + signature_len):
            raise MAVError("invalid MAVLink message length. Got %u expected %u, msgId=%u headerlen=%u" % (len(msgbuf) - (headerlen + 2 + signature_len), mlen, msgId, headerlen))

        if mapkey not in mavlink_map:
            return MAVLink_unknown(msgId, msgbuf)

        # decode the payload
        msgtype = mavlink_map[mapkey]
        order_map = msgtype.orders
        len_map = msgtype.lengths
        crc_extra = msgtype.crc_extra

        # decode the checksum
        try:
            crc: int = self.mav_csum_unpacker.unpack(msgbuf[-(2 + signature_len) :][:2])[0]
        except struct.error as emsg:
            raise MAVError("Unable to unpack MAVLink CRC: %s" % emsg)
        crcbuf = msgbuf[1 : -(2 + signature_len)]
        if True:
            # using CRC extra
            crcbuf.append(crc_extra)
        crc2 = x25crc(crcbuf)
        if crc != crc2.crc and not MAVLINK_IGNORE_CRC:
            raise MAVError("invalid MAVLink CRC in msgID %u 0x%04x should be 0x%04x" % (msgId, crc, crc2.crc))

        sig_ok = False
        if signature_len == MAVLINK_SIGNATURE_BLOCK_LEN:
            self.signing.sig_count += 1
        if self.signing.secret_key is not None:
            accept_signature = False
            if signature_len == MAVLINK_SIGNATURE_BLOCK_LEN:
                sig_ok = self.check_signature(msgbuf, srcSystem, srcComponent)
                accept_signature = sig_ok
                if sig_ok:
                    self.signing.goodsig_count += 1
                else:
                    self.signing.badsig_count += 1
                if not accept_signature and self.signing.allow_unsigned_callback is not None:
                    accept_signature = self.signing.allow_unsigned_callback(self, msgId)
                    if accept_signature:
                        self.signing.unsigned_count += 1
                    else:
                        self.signing.reject_count += 1
            elif self.signing.allow_unsigned_callback is not None:
                accept_signature = self.signing.allow_unsigned_callback(self, msgId)
                if accept_signature:
                    self.signing.unsigned_count += 1
                else:
                    self.signing.reject_count += 1
            if not accept_signature:
                raise MAVError("Invalid signature")

        csize = msgtype.unpacker.size
        mbuf = msgbuf[headerlen : -(2 + signature_len)]
        if len(mbuf) < csize:
            # zero pad to give right size
            mbuf.extend([0] * (csize - len(mbuf)))
        if len(mbuf) < csize:
            raise MAVError("Bad message of type %s length %u needs %s" % (msgtype, len(mbuf), csize))
        mbuf = mbuf[:csize]
        try:
            t: Tuple[Union[bytes, int, float], ...] = msgtype.unpacker.unpack(mbuf)
        except struct.error as emsg:
            raise MAVError("Unable to unpack MAVLink payload type=%s payloadLength=%u: %s" % (msgtype, len(mbuf), emsg))

        tlist: List[Union[bytes, float, int, Sequence[Union[bytes, float, int]]]] = list(t)
        # handle sorted fields
        if True:
            if sum(len_map) == len(len_map):
                # message has no arrays in it
                for i in range(0, len(tlist)):
                    tlist[i] = t[order_map[i]]
            else:
                # message has some arrays
                tlist = []
                for i in range(0, len(order_map)):
                    order = order_map[i]
                    L = len_map[order]
                    tip = sum(len_map[:order])
                    field = t[tip]
                    if L == 1 or isinstance(field, bytes):
                        tlist.append(field)
                    else:
                        tlist.append(list(t[tip : (tip + L)]))

        # terminate any strings
        for i, elem in enumerate(tlist):
            if isinstance(elem, bytes):
                tlist[i] = elem.rstrip(b"\x00")

        # construct the message object
        try:
            # Note that initializers don't follow the Liskov Substitution Principle
            # therefore it can't be typechecked
            m = msgtype(*tlist)  # type: ignore
        except Exception as emsg:
            raise MAVError("Unable to instantiate MAVLink message of type %s : %s" % (msgtype, emsg))
        m._signed = sig_ok
        if m._signed:
            m._link_id = msgbuf[-13]
        m._msgbuf = msgbuf
        m._payload = msgbuf[6 : -(2 + signature_len)]
        m._crc = crc
        m._header = MAVLink_header(msgId, incompat_flags, compat_flags, mlen, seq, srcSystem, srcComponent)
        return m

    def heartbeat_encode(self, custom_mode: int, type: int, autopilot: int, base_mode: int, system_status: int, mavlink_version: int) -> MAVLink_heartbeat_message:
        """
        The heartbeat message shows that a system or component is present and
        responding.         Emitted by the simulator at 1 Hz to allow
        the client to detect connection loss.

        custom_mode               : A bitfield for use for autopilot-specific flags. (type:uint32_t)
        type                      : Vehicle or component type. For the simulator this will be MAV_TYPE_QUADROTOR or MAV_TYPE_GENERIC. (type:uint8_t, values:MAV_TYPE)
        autopilot                 : Autopilot type / class. Use MAV_AUTOPILOT_GENERIC for the simulator. (type:uint8_t, values:MAV_AUTOPILOT)
        base_mode                 : System mode bitmap. (type:uint8_t, values:MAV_MODE_FLAG)
        system_status             : System status flag. (type:uint8_t, values:MAV_STATE)
        mavlink_version           : MAVLink version, not writable by user, gets added by protocol because of magic data type: uint8_t_mavlink_version. Always 3 for v2. (type:uint8_t)

        """
        return MAVLink_heartbeat_message(custom_mode, type, autopilot, base_mode, system_status, mavlink_version)

    def heartbeat_send(self, custom_mode: int, type: int, autopilot: int, base_mode: int, system_status: int, mavlink_version: int, force_mavlink1: bool = False) -> None:
        """
        The heartbeat message shows that a system or component is present and
        responding.         Emitted by the simulator at 1 Hz to allow
        the client to detect connection loss.

        custom_mode               : A bitfield for use for autopilot-specific flags. (type:uint32_t)
        type                      : Vehicle or component type. For the simulator this will be MAV_TYPE_QUADROTOR or MAV_TYPE_GENERIC. (type:uint8_t, values:MAV_TYPE)
        autopilot                 : Autopilot type / class. Use MAV_AUTOPILOT_GENERIC for the simulator. (type:uint8_t, values:MAV_AUTOPILOT)
        base_mode                 : System mode bitmap. (type:uint8_t, values:MAV_MODE_FLAG)
        system_status             : System status flag. (type:uint8_t, values:MAV_STATE)
        mavlink_version           : MAVLink version, not writable by user, gets added by protocol because of magic data type: uint8_t_mavlink_version. Always 3 for v2. (type:uint8_t)

        """
        self.send(self.heartbeat_encode(custom_mode, type, autopilot, base_mode, system_status, mavlink_version), force_mavlink1=force_mavlink1)

    def attitude_encode(self, time_boot_ms: int, roll: float, pitch: float, yaw: float, rollspeed: float, pitchspeed: float, yawspeed: float) -> MAVLink_attitude_message:
        """
        The attitude in the aeronautical frame (right-hand, Z-down / x-front,
        y-right).         Sent by the simulator to convey current
        vehicle orientation and angular rates.

        time_boot_ms              : Timestamp (time since system boot). [ms] (type:uint32_t)
        roll                      : Roll angle (-pi..+pi). [rad] (type:float)
        pitch                     : Pitch angle (-pi..+pi). [rad] (type:float)
        yaw                       : Yaw angle (-pi..+pi). [rad] (type:float)
        rollspeed                 : Roll angular speed. [rad/s] (type:float)
        pitchspeed                : Pitch angular speed. [rad/s] (type:float)
        yawspeed                  : Yaw angular speed. [rad/s] (type:float)

        """
        return MAVLink_attitude_message(time_boot_ms, roll, pitch, yaw, rollspeed, pitchspeed, yawspeed)

    def attitude_send(self, time_boot_ms: int, roll: float, pitch: float, yaw: float, rollspeed: float, pitchspeed: float, yawspeed: float, force_mavlink1: bool = False) -> None:
        """
        The attitude in the aeronautical frame (right-hand, Z-down / x-front,
        y-right).         Sent by the simulator to convey current
        vehicle orientation and angular rates.

        time_boot_ms              : Timestamp (time since system boot). [ms] (type:uint32_t)
        roll                      : Roll angle (-pi..+pi). [rad] (type:float)
        pitch                     : Pitch angle (-pi..+pi). [rad] (type:float)
        yaw                       : Yaw angle (-pi..+pi). [rad] (type:float)
        rollspeed                 : Roll angular speed. [rad/s] (type:float)
        pitchspeed                : Pitch angular speed. [rad/s] (type:float)
        yawspeed                  : Yaw angular speed. [rad/s] (type:float)

        """
        self.send(self.attitude_encode(time_boot_ms, roll, pitch, yaw, rollspeed, pitchspeed, yawspeed), force_mavlink1=force_mavlink1)

    def set_attitude_target_encode(self, time_boot_ms: int, target_system: int, target_component: int, type_mask: int, q: Sequence[float], body_roll_rate: float, body_pitch_rate: float, body_yaw_rate: float, thrust: float) -> MAVLink_set_attitude_target_message:
        """
        Sets a desired vehicle attitude. Used by the contestant control
        software to         command the simulator. The type_mask field
        selects which sub-fields are active.

        time_boot_ms              : Timestamp (time since system boot). Receivers should ignore messages with an incorrect timestamp. [ms] (type:uint32_t)
        target_system             : System ID of the target vehicle (simulator's system ID). (type:uint8_t)
        target_component          : Component ID of the target (e.g. autopilot component). (type:uint8_t)
        type_mask                 : Bitmap to indicate which fields should be ignored. (type:uint8_t, values:ATTITUDE_TARGET_TYPEMASK)
        q                         : Attitude quaternion (w, x, y, z order, zero-rotation is {1, 0, 0, 0}). (type:float)
        body_roll_rate            : Body roll rate. [rad/s] (type:float)
        body_pitch_rate           : Body pitch rate. [rad/s] (type:float)
        body_yaw_rate             : Body yaw rate. [rad/s] (type:float)
        thrust                    : Collective thrust, normalised [0, 1] (-1..1 for vehicles capable of reverse thrust). (type:float)

        """
        return MAVLink_set_attitude_target_message(time_boot_ms, target_system, target_component, type_mask, q, body_roll_rate, body_pitch_rate, body_yaw_rate, thrust)

    def set_attitude_target_send(self, time_boot_ms: int, target_system: int, target_component: int, type_mask: int, q: Sequence[float], body_roll_rate: float, body_pitch_rate: float, body_yaw_rate: float, thrust: float, force_mavlink1: bool = False) -> None:
        """
        Sets a desired vehicle attitude. Used by the contestant control
        software to         command the simulator. The type_mask field
        selects which sub-fields are active.

        time_boot_ms              : Timestamp (time since system boot). Receivers should ignore messages with an incorrect timestamp. [ms] (type:uint32_t)
        target_system             : System ID of the target vehicle (simulator's system ID). (type:uint8_t)
        target_component          : Component ID of the target (e.g. autopilot component). (type:uint8_t)
        type_mask                 : Bitmap to indicate which fields should be ignored. (type:uint8_t, values:ATTITUDE_TARGET_TYPEMASK)
        q                         : Attitude quaternion (w, x, y, z order, zero-rotation is {1, 0, 0, 0}). (type:float)
        body_roll_rate            : Body roll rate. [rad/s] (type:float)
        body_pitch_rate           : Body pitch rate. [rad/s] (type:float)
        body_yaw_rate             : Body yaw rate. [rad/s] (type:float)
        thrust                    : Collective thrust, normalised [0, 1] (-1..1 for vehicles capable of reverse thrust). (type:float)

        """
        self.send(self.set_attitude_target_encode(time_boot_ms, target_system, target_component, type_mask, q, body_roll_rate, body_pitch_rate, body_yaw_rate, thrust), force_mavlink1=force_mavlink1)

    def set_position_target_local_ned_encode(self, time_boot_ms: int, target_system: int, target_component: int, coordinate_frame: int, type_mask: int, x: float, y: float, z: float, vx: float, vy: float, vz: float, afx: float, afy: float, afz: float, yaw: float, yaw_rate: float) -> MAVLink_set_position_target_local_ned_message:
        """
        Sets a desired vehicle position in a local north-east-down coordinate
        frame.         Used by the contestant control software to send
        position / velocity / acceleration         setpoints to the
        simulator. Use type_mask to ignore sub-fields.

        time_boot_ms              : Timestamp (time since system boot). [ms] (type:uint32_t)
        target_system             : System ID of the target vehicle. (type:uint8_t)
        target_component          : Component ID of the target. (type:uint8_t)
        coordinate_frame          : Valid options are: MAV_FRAME_LOCAL_NED, MAV_FRAME_LOCAL_OFFSET_NED,
        MAV_FRAME_BODY_NED, MAV_FRAME_BODY_OFFSET_NED. (type:uint8_t, values:MAV_FRAME)
        type_mask                 : Bitmap to indicate which dimensions should be ignored. (type:uint16_t, values:POSITION_TARGET_TYPEMASK)
        x                         : X position in NED frame (positive north). [m] (type:float)
        y                         : Y position in NED frame (positive east). [m] (type:float)
        z                         : Z position in NED frame (positive down). Use negative values for altitude above ground. [m] (type:float)
        vx                        : X velocity in NED frame. [m/s] (type:float)
        vy                        : Y velocity in NED frame. [m/s] (type:float)
        vz                        : Z velocity in NED frame. [m/s] (type:float)
        afx                       : X acceleration or force (if bit 10 of type_mask is set) in NED frame. [m/s/s] (type:float)
        afy                       : Y acceleration or force in NED frame. [m/s/s] (type:float)
        afz                       : Z acceleration or force in NED frame. [m/s/s] (type:float)
        yaw                       : Yaw setpoint. [rad] (type:float)
        yaw_rate                  : Yaw rate setpoint. [rad/s] (type:float)

        """
        return MAVLink_set_position_target_local_ned_message(time_boot_ms, target_system, target_component, coordinate_frame, type_mask, x, y, z, vx, vy, vz, afx, afy, afz, yaw, yaw_rate)

    def set_position_target_local_ned_send(self, time_boot_ms: int, target_system: int, target_component: int, coordinate_frame: int, type_mask: int, x: float, y: float, z: float, vx: float, vy: float, vz: float, afx: float, afy: float, afz: float, yaw: float, yaw_rate: float, force_mavlink1: bool = False) -> None:
        """
        Sets a desired vehicle position in a local north-east-down coordinate
        frame.         Used by the contestant control software to send
        position / velocity / acceleration         setpoints to the
        simulator. Use type_mask to ignore sub-fields.

        time_boot_ms              : Timestamp (time since system boot). [ms] (type:uint32_t)
        target_system             : System ID of the target vehicle. (type:uint8_t)
        target_component          : Component ID of the target. (type:uint8_t)
        coordinate_frame          : Valid options are: MAV_FRAME_LOCAL_NED, MAV_FRAME_LOCAL_OFFSET_NED,
        MAV_FRAME_BODY_NED, MAV_FRAME_BODY_OFFSET_NED. (type:uint8_t, values:MAV_FRAME)
        type_mask                 : Bitmap to indicate which dimensions should be ignored. (type:uint16_t, values:POSITION_TARGET_TYPEMASK)
        x                         : X position in NED frame (positive north). [m] (type:float)
        y                         : Y position in NED frame (positive east). [m] (type:float)
        z                         : Z position in NED frame (positive down). Use negative values for altitude above ground. [m] (type:float)
        vx                        : X velocity in NED frame. [m/s] (type:float)
        vy                        : Y velocity in NED frame. [m/s] (type:float)
        vz                        : Z velocity in NED frame. [m/s] (type:float)
        afx                       : X acceleration or force (if bit 10 of type_mask is set) in NED frame. [m/s/s] (type:float)
        afy                       : Y acceleration or force in NED frame. [m/s/s] (type:float)
        afz                       : Z acceleration or force in NED frame. [m/s/s] (type:float)
        yaw                       : Yaw setpoint. [rad] (type:float)
        yaw_rate                  : Yaw rate setpoint. [rad/s] (type:float)

        """
        self.send(self.set_position_target_local_ned_encode(time_boot_ms, target_system, target_component, coordinate_frame, type_mask, x, y, z, vx, vy, vz, afx, afy, afz, yaw, yaw_rate), force_mavlink1=force_mavlink1)

    def highres_imu_encode(self, time_usec: int, xacc: float, yacc: float, zacc: float, xgyro: float, ygyro: float, zgyro: float, xmag: float, ymag: float, zmag: float, abs_pressure: float, diff_pressure: float, pressure_alt: float, temperature: float, fields_updated: int, id: int) -> MAVLink_highres_imu_message:
        """
        The IMU readings in SI units in NED body frame.         Sent by the
        simulator to convey current vehicle sensor state.

        time_usec                 : Timestamp (UNIX Epoch time or time since system boot). Microseconds. [us] (type:uint64_t)
        xacc                      : X acceleration. [m/s/s] (type:float)
        yacc                      : Y acceleration. [m/s/s] (type:float)
        zacc                      : Z acceleration. [m/s/s] (type:float)
        xgyro                     : Angular speed around X axis. [rad/s] (type:float)
        ygyro                     : Angular speed around Y axis. [rad/s] (type:float)
        zgyro                     : Angular speed around Z axis. [rad/s] (type:float)
        xmag                      : X magnetic field. [gauss] (type:float)
        ymag                      : Y magnetic field. [gauss] (type:float)
        zmag                      : Z magnetic field. [gauss] (type:float)
        abs_pressure              : Absolute pressure. [hPa] (type:float)
        diff_pressure             : Differential pressure. [hPa] (type:float)
        pressure_alt              : Altitude calculated from pressure. [m] (type:float)
        temperature               : Temperature. [degC] (type:float)
        fields_updated            : Bitmap for fields that have updated since last message; bit 0 = xacc, bit 1 = yacc,
        bit 2 = zacc, bit 3 = xgyro, bit 4 = ygyro, bit 5 = zgyro, bit 6 = xmag, bit 7 = ymag,
        bit 8 = zmag, bit 9 = abs_pressure, bit 10 = diff_pressure, bit 11 = pressure_alt,
        bit 12 = temperature. (type:uint16_t)
        id                        : Id. Ids are numbered from 0 and map to IMUs numbered from 1 (e.g. IMU1 is id=0). (type:uint8_t)

        """
        return MAVLink_highres_imu_message(time_usec, xacc, yacc, zacc, xgyro, ygyro, zgyro, xmag, ymag, zmag, abs_pressure, diff_pressure, pressure_alt, temperature, fields_updated, id)

    def highres_imu_send(self, time_usec: int, xacc: float, yacc: float, zacc: float, xgyro: float, ygyro: float, zgyro: float, xmag: float, ymag: float, zmag: float, abs_pressure: float, diff_pressure: float, pressure_alt: float, temperature: float, fields_updated: int, id: int, force_mavlink1: bool = False) -> None:
        """
        The IMU readings in SI units in NED body frame.         Sent by the
        simulator to convey current vehicle sensor state.

        time_usec                 : Timestamp (UNIX Epoch time or time since system boot). Microseconds. [us] (type:uint64_t)
        xacc                      : X acceleration. [m/s/s] (type:float)
        yacc                      : Y acceleration. [m/s/s] (type:float)
        zacc                      : Z acceleration. [m/s/s] (type:float)
        xgyro                     : Angular speed around X axis. [rad/s] (type:float)
        ygyro                     : Angular speed around Y axis. [rad/s] (type:float)
        zgyro                     : Angular speed around Z axis. [rad/s] (type:float)
        xmag                      : X magnetic field. [gauss] (type:float)
        ymag                      : Y magnetic field. [gauss] (type:float)
        zmag                      : Z magnetic field. [gauss] (type:float)
        abs_pressure              : Absolute pressure. [hPa] (type:float)
        diff_pressure             : Differential pressure. [hPa] (type:float)
        pressure_alt              : Altitude calculated from pressure. [m] (type:float)
        temperature               : Temperature. [degC] (type:float)
        fields_updated            : Bitmap for fields that have updated since last message; bit 0 = xacc, bit 1 = yacc,
        bit 2 = zacc, bit 3 = xgyro, bit 4 = ygyro, bit 5 = zgyro, bit 6 = xmag, bit 7 = ymag,
        bit 8 = zmag, bit 9 = abs_pressure, bit 10 = diff_pressure, bit 11 = pressure_alt,
        bit 12 = temperature. (type:uint16_t)
        id                        : Id. Ids are numbered from 0 and map to IMUs numbered from 1 (e.g. IMU1 is id=0). (type:uint8_t)

        """
        self.send(self.highres_imu_encode(time_usec, xacc, yacc, zacc, xgyro, ygyro, zgyro, xmag, ymag, zmag, abs_pressure, diff_pressure, pressure_alt, temperature, fields_updated, id), force_mavlink1=force_mavlink1)

    def timesync_encode(self, tc1: int, ts1: int) -> MAVLink_timesync_message:
        """
        Time synchronisation message. The simulator sends this with tc1=0 to
        initiate         a sync request. The client echoes it back
        with tc1 set to the current timestamp,         allowing the
        simulator to compute clock offset. Both sides repeat the
        exchange         periodically (recommended: every 5 s).

        tc1                       : Time sync timestamp 1. Set to 0 on the initiating (request) message; set to
        the local timestamp in nanoseconds on the response. [ns] (type:int64_t)
        ts1                       : Time sync timestamp 2. Set to local timestamp in nanoseconds when the message
        is sent. [ns] (type:int64_t)

        """
        return MAVLink_timesync_message(tc1, ts1)

    def timesync_send(self, tc1: int, ts1: int, force_mavlink1: bool = False) -> None:
        """
        Time synchronisation message. The simulator sends this with tc1=0 to
        initiate         a sync request. The client echoes it back
        with tc1 set to the current timestamp,         allowing the
        simulator to compute clock offset. Both sides repeat the
        exchange         periodically (recommended: every 5 s).

        tc1                       : Time sync timestamp 1. Set to 0 on the initiating (request) message; set to
        the local timestamp in nanoseconds on the response. [ns] (type:int64_t)
        ts1                       : Time sync timestamp 2. Set to local timestamp in nanoseconds when the message
        is sent. [ns] (type:int64_t)

        """
        self.send(self.timesync_encode(tc1, ts1), force_mavlink1=force_mavlink1)

    def odometry_encode(self, time_usec: int, frame_id: int, child_frame_id: int, x: float, y: float, z: float, q: Sequence[float], vx: float, vy: float, vz: float, rollspeed: float, pitchspeed: float, yawspeed: float, pose_covariance: Sequence[float], velocity_covariance: Sequence[float], reset_counter: int, estimator_type: int) -> MAVLink_odometry_message:
        """
        Odometry message encoding the position and velocity in a given
        reference frame.         Sent by the simulator to provide
        ground-truth or estimated state for the vehicle.

        time_usec                 : Timestamp (UNIX Epoch time or time since system boot). Microseconds. [us] (type:uint64_t)
        frame_id                  : Coordinate frame of reference for the pose data. (type:uint8_t, values:MAV_FRAME)
        child_frame_id            : Coordinate frame of reference for the velocity data. (type:uint8_t, values:MAV_FRAME)
        x                         : X position in frame_id. [m] (type:float)
        y                         : Y position in frame_id. [m] (type:float)
        z                         : Z position in frame_id. [m] (type:float)
        q                         : Quaternion components (w, x, y, z order) representing vehicle orientation
        in the reference frame. (type:float)
        vx                        : X linear speed in child_frame_id. [m/s] (type:float)
        vy                        : Y linear speed in child_frame_id. [m/s] (type:float)
        vz                        : Z linear speed in child_frame_id. [m/s] (type:float)
        rollspeed                 : Roll angular speed in child_frame_id. [rad/s] (type:float)
        pitchspeed                : Pitch angular speed in child_frame_id. [rad/s] (type:float)
        yawspeed                  : Yaw angular speed in child_frame_id. [rad/s] (type:float)
        pose_covariance           : Row-major representation of a 6×6 pose cross-covariance matrix upper right triangle
        (states: x, y, z, roll, pitch, yaw). Set to NaN if unknown. (type:float)
        velocity_covariance        : Row-major representation of a 6×6 velocity cross-covariance matrix upper right triangle
        (states: vx, vy, vz, rollspeed, pitchspeed, yawspeed). Set to NaN if unknown. (type:float)
        reset_counter             : Estimate reset counter. Increases each time the estimate resets in any of the dimensions
        (position, velocity, attitude). Zero by default. 0-255, rolls over. (type:uint8_t)
        estimator_type            : Type of estimator that is providing the odometry. (type:int8_t, values:MAV_ESTIMATOR_TYPE)

        """
        return MAVLink_odometry_message(time_usec, frame_id, child_frame_id, x, y, z, q, vx, vy, vz, rollspeed, pitchspeed, yawspeed, pose_covariance, velocity_covariance, reset_counter, estimator_type)

    def odometry_send(self, time_usec: int, frame_id: int, child_frame_id: int, x: float, y: float, z: float, q: Sequence[float], vx: float, vy: float, vz: float, rollspeed: float, pitchspeed: float, yawspeed: float, pose_covariance: Sequence[float], velocity_covariance: Sequence[float], reset_counter: int, estimator_type: int, force_mavlink1: bool = False) -> None:
        """
        Odometry message encoding the position and velocity in a given
        reference frame.         Sent by the simulator to provide
        ground-truth or estimated state for the vehicle.

        time_usec                 : Timestamp (UNIX Epoch time or time since system boot). Microseconds. [us] (type:uint64_t)
        frame_id                  : Coordinate frame of reference for the pose data. (type:uint8_t, values:MAV_FRAME)
        child_frame_id            : Coordinate frame of reference for the velocity data. (type:uint8_t, values:MAV_FRAME)
        x                         : X position in frame_id. [m] (type:float)
        y                         : Y position in frame_id. [m] (type:float)
        z                         : Z position in frame_id. [m] (type:float)
        q                         : Quaternion components (w, x, y, z order) representing vehicle orientation
        in the reference frame. (type:float)
        vx                        : X linear speed in child_frame_id. [m/s] (type:float)
        vy                        : Y linear speed in child_frame_id. [m/s] (type:float)
        vz                        : Z linear speed in child_frame_id. [m/s] (type:float)
        rollspeed                 : Roll angular speed in child_frame_id. [rad/s] (type:float)
        pitchspeed                : Pitch angular speed in child_frame_id. [rad/s] (type:float)
        yawspeed                  : Yaw angular speed in child_frame_id. [rad/s] (type:float)
        pose_covariance           : Row-major representation of a 6×6 pose cross-covariance matrix upper right triangle
        (states: x, y, z, roll, pitch, yaw). Set to NaN if unknown. (type:float)
        velocity_covariance        : Row-major representation of a 6×6 velocity cross-covariance matrix upper right triangle
        (states: vx, vy, vz, rollspeed, pitchspeed, yawspeed). Set to NaN if unknown. (type:float)
        reset_counter             : Estimate reset counter. Increases each time the estimate resets in any of the dimensions
        (position, velocity, attitude). Zero by default. 0-255, rolls over. (type:uint8_t)
        estimator_type            : Type of estimator that is providing the odometry. (type:int8_t, values:MAV_ESTIMATOR_TYPE)

        """
        self.send(self.odometry_encode(time_usec, frame_id, child_frame_id, x, y, z, q, vx, vy, vz, rollspeed, pitchspeed, yawspeed, pose_covariance, velocity_covariance, reset_counter, estimator_type), force_mavlink1=force_mavlink1)
